grails-app/domain/com/mbds/grails/Annonce.groovy
package com.mbds.grails

class Annonce {

    String title
    String description
    Double price

    Date dateCreated
    Date lastUpdated

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title       nullable: false, blank: false
        description nullable: false, blank: false
        price       min: 0D
    }

    static mapping = {
        description type: 'text'
        illustrations cascade: 'all-delete-orphan'
    }
}

grails-app/controllers/com/mbds/grails/AnnonceController.groovy
package com.mbds.grails

import grails.core.GrailsApplication
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import org.grails.core.io.ResourceLocator

import static org.springframework.http.HttpStatus.*

@Secured('ROLE_ADMIN')
class AnnonceController {
    def assetResourceLocator
    AnnonceService annonceService
    @Secured(['ROLE_MODO','ROLE_ADMIN'])



    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond annonceService.list(params), model:[annonceCount: annonceService.count(), baseUrl: grailsApplication.config.annonces.illustrations.url]
    }

    @Secured(['ROLE_MODO','ROLE_ADMIN'])
    def show(Long id) {
        respond annonceService.get(id), model: [baseUrl: grailsApplication.config.annonces.illustrations.url]

    }

    def create() {
        respond new Annonce(params), model: [userList: User.list()]
    }

    def save(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }
        HashSet illustrations = new HashSet<>()
        try{
            def downloadfiles = request.getFiles("file")
            if(downloadfiles!=null){
                String pathImage = grailsApplication.config.annonces.illustrations.path.toString()
                println "absolutePath" + pathImage



                downloadfiles.each {
                    downloadfile ->
                        String filename = downloadfile.getOriginalFilename()
                        println "pathImage:" + (pathImage + File.separatorChar + filename)
                        downloadfile.transferTo(new File(pathImage + File.separatorChar + filename))
                        Illustration illu=new Illustration();
                        illu.annonce = annonce
                        illu.filename =   filename
                        if(!filename.isEmpty())
                            illustrations.add(illu)
                }

            }
        }catch(Exception exc){
            exc.printStackTrace()
        }
        try {
            annonce.illustrations =illustrations
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }
    @Secured(['ROLE_MODO','ROLE_ADMIN'])
    def edit(Long id) {
        def userList = User.list()
        respond annonceService.get(id), model: [userList: userList, baseUrl: grailsApplication.config.annonces.illustrations.url]
    }

    def update() {
        def annonce = Annonce.get(params.id)
        annonce.title = params.title
        annonce.description = params.description
        annonce.price = Double.parseDouble(params.price)
        annonce.author = User.get(params.author.id)
        if (annonce == null) {
            notFound()
            return
        }
        HashSet illustrations = new HashSet<>()
        try{
            def downloadfiles = request.getFiles("file")
            if(downloadfiles!=null){
                    String pathImage = grailsApplication.config.annonces.illustrations.path.toString()
                    println "absolutePath" + pathImage



                    downloadfiles.each {
                        downloadfile ->
                            String filename = downloadfile.getOriginalFilename()
                            println "pathImage:" + (pathImage + File.separatorChar + filename)
                            downloadfile.transferTo(new File(pathImage + File.separatorChar + filename))
                            Illustration illu=new Illustration();
                            illu.annonce = annonce
                            illu.filename =   filename
                            if(!filename.isEmpty())
                                illustrations.add(illu)
                    }

            }
        }catch(Exception exc){
            exc.printStackTrace()
        }

        /**
         * 1. Récupérer le fichier dans la requête
         * 2. Sauvegarder le fichier localement
         * 3. Créer un illustration sur le fichier que vous avez sauvegardé
         * 4. Attacher l'illustration nouvellement créée à l'annonce
         */

        try {
            if(!illustrations.isEmpty()){
                annonce.illustrations.clear()
                annonce.illustrations.addAll(illustrations)
            }


            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*'{ respond annonce, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        annonceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/mbds/grails/UserController.groovy
package com.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN','ROLE_MODO'])
class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    @Secured('ROLE_ADMIN')
    def edit(Long id) {
        respond userService.get(id)
    }

    @Secured('ROLE_ADMIN')
    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN')
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
    <nav aria-label="breadcrumb text-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="${createLink(uri: '/')}">
                    <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
                </a>
            </li>
            <li class="breadcrumb-item">
                <g:link class="list" action="index"><span class="fa fa-clipboard-list"></span>&nbsp;<g:message
                  code="default.list.label" args="[entityName]"/></g:link>
            </li>
        </ol>
    </nav>


        <div id="create-annonce" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.annonce}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:uploadForm controller="annonce" action="save" method="POST">
                %{--<fieldset class="form">
                    <f:all bean="annonce"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>--}%
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="form-group row">
                                    <label for="title">Title
                                        <span class="required-indicator">*</span>
                                    </label>
                                    <div class="col-sm-10">
                                        <input class="form-control" type="text" name="title" value="" required="" id="title">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="description">Description
                                        <span class="required-indicator">*</span>
                                    </label>
                                    <div class="col-sm-10">
                                        <input class="form-control" type="text" name="description" value="" required="" id="description">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="price">Price
                                        <span class="required-indicator">*</span>
                                    </label>
                                    <div class="col-sm-10">
                                        <input class="form-control" type="number decimal" name="price" value="" required="" min="0.0" id="price">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="price">Illustrations
                                        <span class="required-indicator">*</span>
                                    </label>
                                    <div class="col-sm-10">
                                        <input multiple type="file" name="file" class="form-control-file" id="file_upload">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="author">Author
                                        <span class="required-indicator">*</span>
                                    </label>
                                    <div class="col-sm-10">
                                        <g:select name="author.id" class="form-control" from="${userList}" optionKey="id" optionValue="username" />
                                    </div>
                                </div>
                            </div>
                            <div class="card-body text-center">
                                <button type="submit" class="btn btn-primary btn-lg btn-block" name="create"
                                        value="Create" id="create">Create
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
            </g:uploadForm>
        </div>
    </body>
</html>

grails-app/views/annonce/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<nav aria-label="breadcrumb text-center">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="${createLink(uri: '/')}">
                <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
            </a>
        </li>
        <li class="breadcrumb-item">
            <g:link class="list" action="index"><span class="fa fa-clipboard-list"></span>&nbsp;<g:message
              code="default.list.label" args="[entityName]"/></g:link>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            <g:link class="create" action="create"><span class="fa fa-plus-circle"></span>&nbsp;<g:message
              code="default.new.label" args="[entityName]"/></g:link>
        </li>
    </ol>
</nav>


<div id="edit-annonce" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.annonce}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:uploadForm controller="annonce" action="update" id="${annonce.id}">
        <g:hiddenField name="version" value="${this.annonce?.version}"/>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="title">Title
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-10">
                                <input class="form-control" type="text" name="title" value="${annonce.title}" required="" id="title">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description">Description
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-10">
                                <input class="form-control" type="text" name="description" value="${annonce.description}" required="" id="description">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price">Price
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-10">
                                <input class="form-control" type="number decimal" name="price" value="${annonce.price}" required="" min="0.0" id="price">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="illustrations">Illustrations</label>
                            <div class="col-sm-10">
                                <g:each in="${annonce.illustrations}" var="illustration" id="illustrations">
                                    <img style="width: 200px" src="${baseUrl + illustration.filename}" />
                                </g:each>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price">Upload files
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-10">
                                <input multiple type="file" name="file" class="form-control-file" id="file_upload">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="author">Author
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-10">
                                <g:select name="author.id" class="form-control" from="${userList}" optionKey="id"
                                          optionValue="username" id="author"/>
                            </div>
                        </div>
                    </div>
                    <div class="card-body text-center">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">${message(code: 'default.button.update.label', default: 'Update')}
                        </button>
                    </div>
                </div>
            </div>

        </div>


    </g:uploadForm>
</div>
</body>
</html>

grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

    <nav aria-label="breadcrumb text-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="${createLink(uri: '/')}">
                    <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
                </a>
            </li>
            <sec:ifAnyGranted roles="ROLE_ADMIN">
                <li class="breadcrumb-item active" aria-current="page">
                    <g:link class="create" action="create"><span class="fa fa-plus-circle"></span>&nbsp;<g:message
                      code="default.new.label" args="[entityName]"/></g:link>
                </li>
            </sec:ifAnyGranted>
        </ol>
    </nav>




        <div id="list-annonce" class="content scaffold-list" role="main">
            <div class="container">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th class="sortable"><a href="/projet/annonce/index?sort=title&amp;max=10&amp;order=asc">Title</a></th>
                        <th class="sortable"><a href="/projet/annonce/index?sort=description&amp;max=10&amp;order=asc">Description</a></th>
                        <th class="sortable"><a href="/projet/annonce/index?sort=price&amp;max=10&amp;order=asc">Price</a></th>
                        <th class="sortable"><a href="/projet/annonce/index?sort=illustrations&amp;max=10&amp;order=asc">Illustrations</a></th>
                        <th class="sortable"><a href="/projet/annonce/index?sort=author&amp;max=10&amp;order=asc">Author</a></th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${annonceList}" var="annonce">
                        <tr class="even">
                            <td><a href="/projet/annonce/show/${annonce.id}">${annonce.title}</a></td>
                            <td>${annonce.description}</td>
                            <td>${annonce.price}</td>
                            <td>
                                <g:each in="${annonce.illustrations}" var="illustration">
                                    <img src="${baseUrl + illustration.filename}" style="width: 50px"/>
                                </g:each>
                            </td>
                            <td><a href="/projet/user/show/${annonce.id}">${annonce.author.username}</a></td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>
                <div class="pagination">
                    <g:paginate total="${annonceCount ?: 0}" />
                </div>
            </div>
        </div>
    </body>
</html>

grails-app/views/annonce/show.gsp
<!DOCTYPE html>
<html>

<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>

<a href="#show-annonce" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>


<nav aria-label="breadcrumb text-center">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="${createLink(uri: '/')}">
                <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
            </a>
        </li>
        <li class="breadcrumb-item">
            <g:link class="list" action="index"><span class="fa fa-clipboard-list"></span>&nbsp;<g:message
              code="default.list.label" args="[entityName]"/></g:link>
        </li>
        <sec:ifAnyGranted roles="ROLE_ADMIN">
            <li class="breadcrumb-item active" aria-current="page">
                <g:link class="create" action="create"><span class="fa fa-plus-circle"></span>&nbsp;<g:message
                  code="default.new.label" args="[entityName]"/></g:link>
            </li>
        </sec:ifAnyGranted>
    </ol>
</nav>


<div class="row">
    <div class="col">
        <div class="card m-5">
            <div class="card-header">
                <h4 class="ml-3">Détail d'une annonce</h4>
            </div>

            <div class="card-body">

                <div class="row">
                    <div class="col-md-4 text-left">
                        Titre :
                    </div>
                    <div class="col-md-4 text-left">
                        ${annonce.title}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Description :
                    </div>
                    <div class="col-md-4 text-left">
                        ${annonce.description}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Prix :
                    </div>
                    <div class="col-md-4 text-left">
                        ${annonce.price}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Illustrations :
                    </div>
                    <div class="col-md-4 text-left">
                        <g:each in="${annonce.illustrations}" var="illustration">
                            <img width="100" style="margin-bottom: 10px;" src="${baseUrl +
                              illustration.filename}"/>
                        </g:each>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Auteur :
                    </div>
                    <div class="col-md-4 text-left">
                        ${annonce.author.username}
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                <button type="submit"
                        class="btn btn-primary" style="width: 100%">
                    <g:link action="edit" resource="${this.annonce}" class="text-white">
                        Modifier
                    </g:link>
                </button>
            </div>
        </div>
    </div>
</div>



</body>
</html>