grails-app/domain/com/mbds/grails/User.groovy
package com.mbds.grails

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [annonces: Annonce]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/com/mbds/grails/UserController.groovy
package com.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN','ROLE_MODO'])
class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    @Secured('ROLE_ADMIN')
    def edit(Long id) {
        respond userService.get(id)
    }

    @Secured('ROLE_ADMIN')
    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN')
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <nav aria-label="breadcrumb text-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="${createLink(uri: '/')}">
                        <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <g:link class="list" action="index"><span class="fa fa-clipboard-list"></span>&nbsp;<g:message
                      code="default.list.label" args="[entityName]"/></g:link>
                </li>
            </ol>
        </nav>


        <div id="create-user" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.user}" method="POST">
                <div class="row">
                   <div class="col-md-12">
                       <div class="card m-5">
                           <div class="card-body">
                               <div class="form-group row">
                                   <div class="col-md-3">
                                       <label for="password">Password
                                           <span class="required-indicator">*</span>
                                       </label>
                                   </div>
                                   <div class="col-md-9">
                                       <input class="form-control full-width" type="password" name="password" required="" value="" id="password">
                                   </div>
                               </div>

                               <div class="form-group row">
                                   <div class="col-md-3">
                                       <label for="username">Username
                                           <span class="required-indicator">*</span>
                                       </label>
                                   </div>
                                   <div class="col-md-9">
                                       <input class="form-control full-width" type="text" name="username" required=""
                                              value="" id="username">
                                   </div>
                               </div>


                               <div class="form-group row">
                                   <div class="col-md-3">
                                       <label for="passwordExpired">Password Expired</label>
                                   </div>
                                   <div class="col-md-9">
                                       <input type="hidden" name="_passwordExpired"><input type="checkbox"
                                                                                           name="passwordExpired"
                                                                                           id="passwordExpired">
                                   </div>
                               </div>


                               <div class="form-group row">
                                   <div class="col-md-3">
                                       <label for="accountLocked">Account Locked</label>
                                   </div>
                                   <div class="col-md-9">
                                       <input type="hidden" name="_accountLocked">
                                       <input type="checkbox"
                                              name="accountLocked"
                                              id="accountLocked">
                                   </div>
                               </div>

                               <div class="form-group row">
                                   <div class="col-md-3">
                                       <label for="accountExpired">Account Expired</label>
                                   </div>
                                   <div class="col-md-9">
                                       <input type="hidden" name="_accountExpired">
                                       <input type="checkbox"
                                              name="accountExpired"
                                              id="accountExpired">
                                   </div>
                               </div>

                               <div class="form-group row">
                                   <div class="col-md-3">
                                       <label for="enabled">Enabled</label>
                                   </div>
                                   <div class="col-md-9">
                                       <input type="hidden" name="_enabled">
                                       <input type="checkbox"
                                              name="enabled"
                                              checked="checked"
                                              id="enabled">
                                   </div>
                               </div>

                               <div class="form-group row">
                                   <div class="col-md-3">
                                       <label for="annonces">Annonces</label>
                                   </div>
                                   <div class="col-md-9">
                                       <ul></ul><a href="/projet/annonce/create?user.id=">Add Annonce</a>
                                   </div>
                               </div>

                           </div>
                           <div class="card-footer text-muted">
                               <g:submitButton name="create" class="btn btn-primary btn-lg btn-block" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                           </div>
                       </div>
                   </div>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                           default="Skip to content&hellip;"/></a>
<nav aria-label="breadcrumb text-center">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="${createLink(uri: '/')}">
                <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
            </a>
        </li>
        <li class="breadcrumb-item">
            <g:link class="list" action="index"><span class="fa fa-clipboard-list"></span>&nbsp;<g:message
                    code="default.list.label" args="[entityName]"/></g:link>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            <g:link class="create" action="create"><span class="fa fa-plus-circle"></span>&nbsp;<g:message
                    code="default.new.label" args="[entityName]"/></g:link>
        </li>
    </ol>
</nav>


<div id="edit-user" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.user}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.user}" method="PUT">
        <g:hiddenField name="version" value="${this.user?.version}"/>

        <div class="row">
            <div class="col-md-12">
                <div class="card m-5">
                    <div class="card-body">

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label for="username">Username
                                    <span class="required-indicator">*</span>
                                </label>
                            </div>

                            <div class="col-md-9">
                                <input class="form-control full-width" type="text" name="username" required=""
                                       value="${user.username}" id="username">
                            </div>
                        </div>


                        <div class="form-group row">
                            <div class="col-md-3">
                                <label for="passwordExpired">Mot de passe expiré</label>
                            </div>

                            <div class="col-md-9">
                                <g:radioGroup name="passwordExpired" values="[true, false]"
                                              value="${user.passwordExpired}">
                                    <p><g:message
                                            code="${it.label == "Radio true" ? "Vrai" : "Faux"}"/>: ${it.radio}</p>
                                </g:radioGroup>
                            </div>
                        </div>


                        <div class="form-group row">
                            <div class="col-md-3">
                                <label for="accountLocked">Compte verouillé</label>
                            </div>

                            <div class="col-md-9">
                                <g:radioGroup name="accountLocked" values="[true, false]" value="${user.accountLocked}">
                                    <p><g:message
                                            code="${it.label == "Radio true" ? "Vrai" : "Faux"}"/>: ${it.radio}</p>
                                </g:radioGroup>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label for="accountExpired">Compte expiré</label>
                            </div>

                            <div class="col-md-9">
                                <g:radioGroup name="accountExpired" values="[true, false]"
                                              value="${user.accountExpired}">
                                    <p><g:message
                                            code="${it.label == "Radio true" ? "Vrai" : "Faux"}"/>: ${it.radio}</p>
                                </g:radioGroup>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label for="enabled">Compte activé</label>
                            </div>

                            <div class="col-md-9">
                                <g:radioGroup name="enabled" values="[true, false]" value="${user.enabled}">
                                    <p><g:message
                                            code="${it.label == "Radio true" ? "Vrai" : "Faux"}"/>: ${it.radio}</p>
                                </g:radioGroup>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label>Annonces</label>
                            </div>

                            <div class="col-md-9">
                                <ul></ul><a href="/projet/annonce/create?user.id=">Add Annonce</a>
                            </div>
                        </div>

                    </div>

                    <div class="card-footer text-muted">
                        <g:submitButton name="create" class="btn btn-primary btn-lg btn-block"
                                        value="${message(code: 'default.button.update.label', default: 'Update')}"/>
                    </div>
                </div>
            </div>
        </div>
    </g:form>
</div>
</body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

    <nav aria-label="breadcrumb text-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="${createLink(uri: '/')}">
                    <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
                </a>
            </li>
            <li class="breadcrumb-item">
                <g:link class="create" action="create"><span class="fa fa-plus-circle"></span>&nbsp;<g:message
              code="default.new.label" args="[entityName]" /></g:link>
            </li>
        </ol>
    </nav>

        <div id="list-user" class="content scaffold-list" role="main">
            <div class="container">
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th class="sortable" scope="col">
                            <a href="/projet/user/index?sort=username&amp;max=10&amp;order=asc">Nom d'utilisateur</a>
                        </th>
                        <th class="sortable" scope="col">
                            <a href="/projet/user/index?sort=passwordExpired&amp;max=10&amp;order=asc">Mot de passe expiré</a>
                        </th>
                        <th class="sortable" scope="col">
                            <a href="/projet/user/index?sort=accountLocked&amp;max=10&amp;order=asc">Compte verrouillé</a>
                        </th>
                        <th class="sortable" scope="col">
                            <a href="/projet/user/index?sort=accountExpired&amp;max=10&amp;order=asc">Compte expiré</a>
                        </th>
                        <th class="sortable" scope="col">
                            <a href="/projet/user/index?sort=enabled&amp;max=10&amp;order=asc">Activé</a>
                        </th>
                        <th>Annonces</th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${userList}" var="user">
                        <tr class="even">
                            <td class="text-center"><a href="/projet/user/show/${user.id}">${user.username}</a></td>
                            <td class="text-center">${user.passwordExpired}</td>
                            <td class="text-center">${user.accountLocked}</td>
                            <td class="text-center">${user.accountExpired}</td>
                            <td class="text-center">${user.enabled}</td>
                            <td class="p-5">
                                <ul>
                                    <g:each in="${user.annonces}" var="annonce">
                                        <span class="fa fa-chevron-circle-right"></span>
                                                <a href="/projet/annonce/show/${annonce.id}">${annonce.title}</a>
                                        <br>
                                    </g:each>
                                </ul>
                            </td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>

                <div class="pagination">
                    <g:paginate total="${userCount ?: 0}" />
                </div>
            </div>
            %{--<h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${userList}" />--}%
        </div>
    </body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<nav aria-label="breadcrumb text-center">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="${createLink(uri: '/')}">
                <span class="fa fa-home"></span>&nbsp;<g:message code="default.home.label"/>
            </a>
        </li>
        <li class="breadcrumb-item">
            <g:link class="list" action="index"><span class="fa fa-clipboard-list"></span>&nbsp;<g:message
              code="default.list.label" args="[entityName]"/></g:link>
        </li>
        <sec:ifAnyGranted roles="ROLE_ADMIN">
            <li class="breadcrumb-item active" aria-current="page">
                <g:link class="create" action="create"><span class="fa fa-plus-circle"></span>&nbsp;<g:message
                  code="default.new.label" args="[entityName]"/></g:link>
            </li>
        </sec:ifAnyGranted>
    </ol>
</nav>


<div class="row">
    <div class="col">
        <div class="card m-5">
            <div class="card-header">
                <h4 class="ml-3">Détail d'un utilisateur</h4>
            </div>

            <div class="card-body">

                <div class="row">
                    <div class="col-md-4 text-left">
                        Nom de l'utilisateur :
                    </div>
                    <div class="col-md-4 text-left">
                        ${user.username}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Mot de passe expiré :
                    </div>
                    <div class="col-md-4 text-left">
                        ${user.passwordExpired}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Compte verouillé :
                    </div>
                    <div class="col-md-4 text-left">
                        ${user.accountLocked}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Compte expiré :
                    </div>
                    <div class="col-md-4 text-left">
                        ${user.accountExpired}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-4 text-left">
                        Activé :
                    </div>
                    <div class="col-md-4 text-left">
                        ${user.enabled}
                    </div>
                </div>
                <hr>

                <div class="row">
                    <div class="col-md-4 text-left">
                        Annonces :
                    </div>
                    <div class="col-md-4 text-left">
                        <g:each in="${user.annonces}" var="annonce">
                           <span class="fa fa-chevron-circle-right"></span>
                            <a class="home"
                               href="${createLink(uri: '/annonce/show/'+annonce.id)}">${annonce.title}</a> <br>
                        </g:each>
                    </div>
                </div>

            </div>
            <div class="card-footer text-muted">
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <button type="submit"
                            class="btn btn-primary" style="width: 100%">
                        <g:link action="edit" resource="${this.user}" class="text-white">
                            Modifier
                        </g:link>
                    </button>
                </sec:ifAnyGranted>
            </div>
        </div>
    </div>
</div>

</body>
</html>